fix(render-test): fix "gulp build" error: Cannot find module 'xxx/lib/js/test/render/TestRender.js'
reason
gulpfile.js require xxx/testRender.js, and it require xxx/lib/xxx/TestRender.js, but lib/xxx
doesn't exist because bsb compile not be executed yet

solution
compile bsb before exec gulp tasks,
so that gulp task can dependent on reason!

(chore: remove commitlint)